import "./globals.css";
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import ReactQuery from "@/components/ReactQuery";
import NextAuthProvider from "@/components/NextAuthProvider";
import { Session } from "next-auth";
import { ReactNode } from "react";
import LoadingPage from "@/components/LoadingPage";
import { Toaster } from "react-hot-toast";

interface NextAuthProps {
  children: ReactNode;
  session: Session | null | undefined;
}

const inter = Poppins({ subsets: ["latin"], weight: "300" });

export const metadata: Metadata = {
  title: "MySchool",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }: NextAuthProps) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <NextAuthProvider session={session}>
          <ReactQuery>
            <LoadingPage>
              <Toaster position="bottom-center" reverseOrder={false} />
              {children}
            </LoadingPage>
          </ReactQuery>
        </NextAuthProvider>
      </body>
    </html>
  );
}
